### ISSUE TITLE
difference between master and published package in PyPi

### ISSUE THREAD

**Issue by ybenitezf** [cgauge/Flask-AWSCognito#10]
I ask because there are features in master that I would like to use in one of my projects. For example `AWSCognitoAuthentication.get_user_info`

**Comment by babaMar** [comment]
Hi @ybenitezf thanks for your interest. I'm not a developer anymore at `cgauge` so can't do much with it. Maybe @cpersico can look into this (cc @customergauge)

**Comment by ybenitezf** [comment]
Ok, thanks
