### ISSUE TITLE
Can we use this library with a Cognito client with no "Client Secret"? 

### ISSUE THREAD

**Issue by devireds** [cgauge/Flask-AWSCognito#5]
Hello, 

According to my understanding, this library needs the  "Client Secret". Can we use this library without Client Secret?

Thank you,
SaiJeevan

**Comment by babaMar** [comment]
If you only need to verify the token signature (the token sent to authenticate the request) it should work without the `user_pool_client_secret`, although it might be requested by the app config, so maybe with a dummy entry for that.

In any case, I really suggest going through the [AWS Cognito documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html) before using any library.
